services:
  database:
    image: postgres
    container_name: shopper_api_database
    restart: always
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  node:
    container_name: shopper_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - .env

volumes:
  postgres: 